#!/usr/bin/env python3
from sys import stdin, stdout
for line in stdin.readlines():
    a, op, b = line.split(' ')
    # stdout.write(str(m[op](int(a), int(b))) + '\n')
    match op:
        case '+': res = str(int(a)+int(b)) + '\n'
        case '-': res = str(int(a)-int(b)) + '\n'
        case '*': res = str(int(a)*int(b)) + '\n'
    stdout.write(res)
